//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webPrueba.ServicioChat {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaMensaje", Namespace="http://schemas.datacontract.org/2004/07/ServicioChat")]
    [System.SerializableAttribute()]
    public partial class ListaMensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoMensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoMensaje {
            get {
                return this.TextoMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoMensajeField, value) != true)) {
                    this.TextoMensajeField = value;
                    this.RaisePropertyChanged("TextoMensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chat", Namespace="http://schemas.datacontract.org/2004/07/ServicioChat")]
    [System.SerializableAttribute()]
    public partial class Chat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CalificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstTecladoEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstTecladoIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdChatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webPrueba.ServicioChat.Mensaje[] ListaMensajesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimoMensajeEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimoMensajeIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dirIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webPrueba.ServicioChat.Cliente pObjClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webPrueba.ServicioChat.Empleado pObjEmpleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Calificacion {
            get {
                return this.CalificacionField;
            }
            set {
                if ((this.CalificacionField.Equals(value) != true)) {
                    this.CalificacionField = value;
                    this.RaisePropertyChanged("Calificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentario {
            get {
                return this.ComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioField, value) != true)) {
                    this.ComentarioField = value;
                    this.RaisePropertyChanged("Comentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComentarioI {
            get {
                return this.ComentarioIField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioIField, value) != true)) {
                    this.ComentarioIField = value;
                    this.RaisePropertyChanged("ComentarioI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstTecladoE {
            get {
                return this.EstTecladoEField;
            }
            set {
                if ((this.EstTecladoEField.Equals(value) != true)) {
                    this.EstTecladoEField = value;
                    this.RaisePropertyChanged("EstTecladoE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstTecladoI {
            get {
                return this.EstTecladoIField;
            }
            set {
                if ((this.EstTecladoIField.Equals(value) != true)) {
                    this.EstTecladoIField = value;
                    this.RaisePropertyChanged("EstTecladoI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaAtencion {
            get {
                return this.FechaAtencionField;
            }
            set {
                if ((this.FechaAtencionField.Equals(value) != true)) {
                    this.FechaAtencionField = value;
                    this.RaisePropertyChanged("FechaAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFinal {
            get {
                return this.FechaFinalField;
            }
            set {
                if ((this.FechaFinalField.Equals(value) != true)) {
                    this.FechaFinalField = value;
                    this.RaisePropertyChanged("FechaFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdChat {
            get {
                return this.IdChatField;
            }
            set {
                if ((this.IdChatField.Equals(value) != true)) {
                    this.IdChatField = value;
                    this.RaisePropertyChanged("IdChat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webPrueba.ServicioChat.Mensaje[] ListaMensajes {
            get {
                return this.ListaMensajesField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaMensajesField, value) != true)) {
                    this.ListaMensajesField = value;
                    this.RaisePropertyChanged("ListaMensajes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimoMensajeE {
            get {
                return this.UltimoMensajeEField;
            }
            set {
                if ((this.UltimoMensajeEField.Equals(value) != true)) {
                    this.UltimoMensajeEField = value;
                    this.RaisePropertyChanged("UltimoMensajeE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimoMensajeI {
            get {
                return this.UltimoMensajeIField;
            }
            set {
                if ((this.UltimoMensajeIField.Equals(value) != true)) {
                    this.UltimoMensajeIField = value;
                    this.RaisePropertyChanged("UltimoMensajeI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dirIp {
            get {
                return this.dirIpField;
            }
            set {
                if ((object.ReferenceEquals(this.dirIpField, value) != true)) {
                    this.dirIpField = value;
                    this.RaisePropertyChanged("dirIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webPrueba.ServicioChat.Cliente pObjCliente {
            get {
                return this.pObjClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.pObjClienteField, value) != true)) {
                    this.pObjClienteField = value;
                    this.RaisePropertyChanged("pObjCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webPrueba.ServicioChat.Empleado pObjEmpleado {
            get {
                return this.pObjEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.pObjEmpleadoField, value) != true)) {
                    this.pObjEmpleadoField = value;
                    this.RaisePropertyChanged("pObjEmpleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/ServicioChat")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailCliente {
            get {
                return this.EmailClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailClienteField, value) != true)) {
                    this.EmailClienteField = value;
                    this.RaisePropertyChanged("EmailCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaIngreso {
            get {
                return this.FechaIngresoField;
            }
            set {
                if ((this.FechaIngresoField.Equals(value) != true)) {
                    this.FechaIngresoField = value;
                    this.RaisePropertyChanged("FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelCliente {
            get {
                return this.TelClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.TelClienteField, value) != true)) {
                    this.TelClienteField = value;
                    this.RaisePropertyChanged("TelCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/ServicioChat")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmpleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoAtencion {
            get {
                return this.EstadoAtencionField;
            }
            set {
                if ((this.EstadoAtencionField.Equals(value) != true)) {
                    this.EstadoAtencionField = value;
                    this.RaisePropertyChanged("EstadoAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleado {
            get {
                return this.IdEmpleadoField;
            }
            set {
                if ((this.IdEmpleadoField.Equals(value) != true)) {
                    this.IdEmpleadoField = value;
                    this.RaisePropertyChanged("IdEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpleado {
            get {
                return this.NombreEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmpleadoField, value) != true)) {
                    this.NombreEmpleadoField = value;
                    this.RaisePropertyChanged("NombreEmpleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://schemas.datacontract.org/2004/07/ServicioChat")]
    [System.SerializableAttribute()]
    public partial class Mensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LeidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string linkMsjField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Leido {
            get {
                return this.LeidoField;
            }
            set {
                if ((this.LeidoField.Equals(value) != true)) {
                    this.LeidoField = value;
                    this.RaisePropertyChanged("Leido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoMensaje {
            get {
                return this.TextoMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoMensajeField, value) != true)) {
                    this.TextoMensajeField = value;
                    this.RaisePropertyChanged("TextoMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string linkMsj {
            get {
                return this.linkMsjField;
            }
            set {
                if ((object.ReferenceEquals(this.linkMsjField, value) != true)) {
                    this.linkMsjField = value;
                    this.RaisePropertyChanged("linkMsj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaCliente", Namespace="http://schemas.datacontract.org/2004/07/ServicioChat")]
    [System.SerializableAttribute()]
    public partial class ListaCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CalificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdChatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimoMensajeEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimoMensajeIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dirIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Calificacion {
            get {
                return this.CalificacionField;
            }
            set {
                if ((this.CalificacionField.Equals(value) != true)) {
                    this.CalificacionField = value;
                    this.RaisePropertyChanged("Calificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailCliente {
            get {
                return this.EmailClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailClienteField, value) != true)) {
                    this.EmailClienteField = value;
                    this.RaisePropertyChanged("EmailCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaAtencion {
            get {
                return this.FechaAtencionField;
            }
            set {
                if ((this.FechaAtencionField.Equals(value) != true)) {
                    this.FechaAtencionField = value;
                    this.RaisePropertyChanged("FechaAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFinal {
            get {
                return this.FechaFinalField;
            }
            set {
                if ((this.FechaFinalField.Equals(value) != true)) {
                    this.FechaFinalField = value;
                    this.RaisePropertyChanged("FechaFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaIngreso {
            get {
                return this.FechaIngresoField;
            }
            set {
                if ((this.FechaIngresoField.Equals(value) != true)) {
                    this.FechaIngresoField = value;
                    this.RaisePropertyChanged("FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdChat {
            get {
                return this.IdChatField;
            }
            set {
                if ((this.IdChatField.Equals(value) != true)) {
                    this.IdChatField = value;
                    this.RaisePropertyChanged("IdChat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelCliente {
            get {
                return this.TelClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.TelClienteField, value) != true)) {
                    this.TelClienteField = value;
                    this.RaisePropertyChanged("TelCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimoMensajeE {
            get {
                return this.UltimoMensajeEField;
            }
            set {
                if ((this.UltimoMensajeEField.Equals(value) != true)) {
                    this.UltimoMensajeEField = value;
                    this.RaisePropertyChanged("UltimoMensajeE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimoMensajeI {
            get {
                return this.UltimoMensajeIField;
            }
            set {
                if ((this.UltimoMensajeIField.Equals(value) != true)) {
                    this.UltimoMensajeIField = value;
                    this.RaisePropertyChanged("UltimoMensajeI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dirIp {
            get {
                return this.dirIpField;
            }
            set {
                if ((object.ReferenceEquals(this.dirIpField, value) != true)) {
                    this.dirIpField = value;
                    this.RaisePropertyChanged("dirIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioChat.IWebChat")]
    public interface IWebChat {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/Obtenerservicio", ReplyAction="http://tempuri.org/IWebChat/ObtenerservicioResponse")]
        int Obtenerservicio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/Obtenerservicio", ReplyAction="http://tempuri.org/IWebChat/ObtenerservicioResponse")]
        System.Threading.Tasks.Task<int> ObtenerservicioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/RegistrarUsuarioWeb", ReplyAction="http://tempuri.org/IWebChat/RegistrarUsuarioWebResponse")]
        void RegistrarUsuarioWeb(string pNombre, string pTelefono, string pEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/RegistrarUsuarioWeb", ReplyAction="http://tempuri.org/IWebChat/RegistrarUsuarioWebResponse")]
        System.Threading.Tasks.Task RegistrarUsuarioWebAsync(string pNombre, string pTelefono, string pEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/RegistrarUsuarioInterno", ReplyAction="http://tempuri.org/IWebChat/RegistrarUsuarioInternoResponse")]
        int RegistrarUsuarioInterno(int pid, string pNombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/RegistrarUsuarioInterno", ReplyAction="http://tempuri.org/IWebChat/RegistrarUsuarioInternoResponse")]
        System.Threading.Tasks.Task<int> RegistrarUsuarioInternoAsync(int pid, string pNombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/CrearChat", ReplyAction="http://tempuri.org/IWebChat/CrearChatResponse")]
        int CrearChat(string pNombre, string pTelefono, string pEmail, string pIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/CrearChat", ReplyAction="http://tempuri.org/IWebChat/CrearChatResponse")]
        System.Threading.Tasks.Task<int> CrearChatAsync(string pNombre, string pTelefono, string pEmail, string pIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/CrearMensaje", ReplyAction="http://tempuri.org/IWebChat/CrearMensajeResponse")]
        int CrearMensaje(int pIdChat, string pTipo, string pTextoMensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/CrearMensaje", ReplyAction="http://tempuri.org/IWebChat/CrearMensajeResponse")]
        System.Threading.Tasks.Task<int> CrearMensajeAsync(int pIdChat, string pTipo, string pTextoMensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/RecibirMensajes", ReplyAction="http://tempuri.org/IWebChat/RecibirMensajesResponse")]
        webPrueba.ServicioChat.ListaMensaje[] RecibirMensajes(int pIdChat, string pTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/RecibirMensajes", ReplyAction="http://tempuri.org/IWebChat/RecibirMensajesResponse")]
        System.Threading.Tasks.Task<webPrueba.ServicioChat.ListaMensaje[]> RecibirMensajesAsync(int pIdChat, string pTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtenerChat", ReplyAction="http://tempuri.org/IWebChat/ObtenerChatResponse")]
        webPrueba.ServicioChat.Chat ObtenerChat(int pIdChat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtenerChat", ReplyAction="http://tempuri.org/IWebChat/ObtenerChatResponse")]
        System.Threading.Tasks.Task<webPrueba.ServicioChat.Chat> ObtenerChatAsync(int pIdChat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/RegistraSalidaUsuarioWeb", ReplyAction="http://tempuri.org/IWebChat/RegistraSalidaUsuarioWebResponse")]
        int RegistraSalidaUsuarioWeb(int pidChat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/RegistraSalidaUsuarioWeb", ReplyAction="http://tempuri.org/IWebChat/RegistraSalidaUsuarioWebResponse")]
        System.Threading.Tasks.Task<int> RegistraSalidaUsuarioWebAsync(int pidChat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/CerrarChat", ReplyAction="http://tempuri.org/IWebChat/CerrarChatResponse")]
        int CerrarChat(int pidChat, int pCalifica, string pComentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/CerrarChat", ReplyAction="http://tempuri.org/IWebChat/CerrarChatResponse")]
        System.Threading.Tasks.Task<int> CerrarChatAsync(int pidChat, int pCalifica, string pComentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/RegistraSalidaUsuarioInterno", ReplyAction="http://tempuri.org/IWebChat/RegistraSalidaUsuarioInternoResponse")]
        int RegistraSalidaUsuarioInterno(int pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/RegistraSalidaUsuarioInterno", ReplyAction="http://tempuri.org/IWebChat/RegistraSalidaUsuarioInternoResponse")]
        System.Threading.Tasks.Task<int> RegistraSalidaUsuarioInternoAsync(int pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/HabilitarUsuarioInterno", ReplyAction="http://tempuri.org/IWebChat/HabilitarUsuarioInternoResponse")]
        int HabilitarUsuarioInterno(int pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/HabilitarUsuarioInterno", ReplyAction="http://tempuri.org/IWebChat/HabilitarUsuarioInternoResponse")]
        System.Threading.Tasks.Task<int> HabilitarUsuarioInternoAsync(int pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtenerListaClientes", ReplyAction="http://tempuri.org/IWebChat/ObtenerListaClientesResponse")]
        webPrueba.ServicioChat.ListaCliente[] ObtenerListaClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtenerListaClientes", ReplyAction="http://tempuri.org/IWebChat/ObtenerListaClientesResponse")]
        System.Threading.Tasks.Task<webPrueba.ServicioChat.ListaCliente[]> ObtenerListaClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/verificar_chat", ReplyAction="http://tempuri.org/IWebChat/verificar_chatResponse")]
        int verificar_chat(int idChat, string pTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/verificar_chat", ReplyAction="http://tempuri.org/IWebChat/verificar_chatResponse")]
        System.Threading.Tasks.Task<int> verificar_chatAsync(int idChat, string pTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtenerNombre", ReplyAction="http://tempuri.org/IWebChat/ObtenerNombreResponse")]
        string ObtenerNombre(int pidChat, string pTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtenerNombre", ReplyAction="http://tempuri.org/IWebChat/ObtenerNombreResponse")]
        System.Threading.Tasks.Task<string> ObtenerNombreAsync(int pidChat, string pTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/verificarteclado", ReplyAction="http://tempuri.org/IWebChat/verificartecladoResponse")]
        int verificarteclado(int pidChat, string pTipo, int pestado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/verificarteclado", ReplyAction="http://tempuri.org/IWebChat/verificartecladoResponse")]
        System.Threading.Tasks.Task<int> verificartecladoAsync(int pidChat, string pTipo, int pestado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/AsignarChat", ReplyAction="http://tempuri.org/IWebChat/AsignarChatResponse")]
        int AsignarChat(int pIdChat, int pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/AsignarChat", ReplyAction="http://tempuri.org/IWebChat/AsignarChatResponse")]
        System.Threading.Tasks.Task<int> AsignarChatAsync(int pIdChat, int pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/UploadFile", ReplyAction="http://tempuri.org/IWebChat/UploadFileResponse")]
        void UploadFile(System.IO.Stream stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/UploadFile", ReplyAction="http://tempuri.org/IWebChat/UploadFileResponse")]
        System.Threading.Tasks.Task UploadFileAsync(System.IO.Stream stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtieneRuta", ReplyAction="http://tempuri.org/IWebChat/ObtieneRutaResponse")]
        string ObtieneRuta(int pIdChat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtieneRuta", ReplyAction="http://tempuri.org/IWebChat/ObtieneRutaResponse")]
        System.Threading.Tasks.Task<string> ObtieneRutaAsync(int pIdChat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtieneRutaF", ReplyAction="http://tempuri.org/IWebChat/ObtieneRutaFResponse")]
        string ObtieneRutaF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtieneRutaF", ReplyAction="http://tempuri.org/IWebChat/ObtieneRutaFResponse")]
        System.Threading.Tasks.Task<string> ObtieneRutaFAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtenerListaEmpleados", ReplyAction="http://tempuri.org/IWebChat/ObtenerListaEmpleadosResponse")]
        webPrueba.ServicioChat.Empleado[] ObtenerListaEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtenerListaEmpleados", ReplyAction="http://tempuri.org/IWebChat/ObtenerListaEmpleadosResponse")]
        System.Threading.Tasks.Task<webPrueba.ServicioChat.Empleado[]> ObtenerListaEmpleadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtenerListaChats", ReplyAction="http://tempuri.org/IWebChat/ObtenerListaChatsResponse")]
        webPrueba.ServicioChat.Chat[] ObtenerListaChats();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtenerListaChats", ReplyAction="http://tempuri.org/IWebChat/ObtenerListaChatsResponse")]
        System.Threading.Tasks.Task<webPrueba.ServicioChat.Chat[]> ObtenerListaChatsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/cambiarEstado", ReplyAction="http://tempuri.org/IWebChat/cambiarEstadoResponse")]
        int cambiarEstado(int idEmp, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/cambiarEstado", ReplyAction="http://tempuri.org/IWebChat/cambiarEstadoResponse")]
        System.Threading.Tasks.Task<int> cambiarEstadoAsync(int idEmp, int estado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebChatChannel : webPrueba.ServicioChat.IWebChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebChatClient : System.ServiceModel.ClientBase<webPrueba.ServicioChat.IWebChat>, webPrueba.ServicioChat.IWebChat {
        
        public WebChatClient() {
        }
        
        public WebChatClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebChatClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebChatClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebChatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Obtenerservicio() {
            return base.Channel.Obtenerservicio();
        }
        
        public System.Threading.Tasks.Task<int> ObtenerservicioAsync() {
            return base.Channel.ObtenerservicioAsync();
        }
        
        public void RegistrarUsuarioWeb(string pNombre, string pTelefono, string pEmail) {
            base.Channel.RegistrarUsuarioWeb(pNombre, pTelefono, pEmail);
        }
        
        public System.Threading.Tasks.Task RegistrarUsuarioWebAsync(string pNombre, string pTelefono, string pEmail) {
            return base.Channel.RegistrarUsuarioWebAsync(pNombre, pTelefono, pEmail);
        }
        
        public int RegistrarUsuarioInterno(int pid, string pNombre) {
            return base.Channel.RegistrarUsuarioInterno(pid, pNombre);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarUsuarioInternoAsync(int pid, string pNombre) {
            return base.Channel.RegistrarUsuarioInternoAsync(pid, pNombre);
        }
        
        public int CrearChat(string pNombre, string pTelefono, string pEmail, string pIp) {
            return base.Channel.CrearChat(pNombre, pTelefono, pEmail, pIp);
        }
        
        public System.Threading.Tasks.Task<int> CrearChatAsync(string pNombre, string pTelefono, string pEmail, string pIp) {
            return base.Channel.CrearChatAsync(pNombre, pTelefono, pEmail, pIp);
        }
        
        public int CrearMensaje(int pIdChat, string pTipo, string pTextoMensaje) {
            return base.Channel.CrearMensaje(pIdChat, pTipo, pTextoMensaje);
        }
        
        public System.Threading.Tasks.Task<int> CrearMensajeAsync(int pIdChat, string pTipo, string pTextoMensaje) {
            return base.Channel.CrearMensajeAsync(pIdChat, pTipo, pTextoMensaje);
        }
        
        public webPrueba.ServicioChat.ListaMensaje[] RecibirMensajes(int pIdChat, string pTipo) {
            return base.Channel.RecibirMensajes(pIdChat, pTipo);
        }
        
        public System.Threading.Tasks.Task<webPrueba.ServicioChat.ListaMensaje[]> RecibirMensajesAsync(int pIdChat, string pTipo) {
            return base.Channel.RecibirMensajesAsync(pIdChat, pTipo);
        }
        
        public webPrueba.ServicioChat.Chat ObtenerChat(int pIdChat) {
            return base.Channel.ObtenerChat(pIdChat);
        }
        
        public System.Threading.Tasks.Task<webPrueba.ServicioChat.Chat> ObtenerChatAsync(int pIdChat) {
            return base.Channel.ObtenerChatAsync(pIdChat);
        }
        
        public int RegistraSalidaUsuarioWeb(int pidChat) {
            return base.Channel.RegistraSalidaUsuarioWeb(pidChat);
        }
        
        public System.Threading.Tasks.Task<int> RegistraSalidaUsuarioWebAsync(int pidChat) {
            return base.Channel.RegistraSalidaUsuarioWebAsync(pidChat);
        }
        
        public int CerrarChat(int pidChat, int pCalifica, string pComentario) {
            return base.Channel.CerrarChat(pidChat, pCalifica, pComentario);
        }
        
        public System.Threading.Tasks.Task<int> CerrarChatAsync(int pidChat, int pCalifica, string pComentario) {
            return base.Channel.CerrarChatAsync(pidChat, pCalifica, pComentario);
        }
        
        public int RegistraSalidaUsuarioInterno(int pid) {
            return base.Channel.RegistraSalidaUsuarioInterno(pid);
        }
        
        public System.Threading.Tasks.Task<int> RegistraSalidaUsuarioInternoAsync(int pid) {
            return base.Channel.RegistraSalidaUsuarioInternoAsync(pid);
        }
        
        public int HabilitarUsuarioInterno(int pid) {
            return base.Channel.HabilitarUsuarioInterno(pid);
        }
        
        public System.Threading.Tasks.Task<int> HabilitarUsuarioInternoAsync(int pid) {
            return base.Channel.HabilitarUsuarioInternoAsync(pid);
        }
        
        public webPrueba.ServicioChat.ListaCliente[] ObtenerListaClientes() {
            return base.Channel.ObtenerListaClientes();
        }
        
        public System.Threading.Tasks.Task<webPrueba.ServicioChat.ListaCliente[]> ObtenerListaClientesAsync() {
            return base.Channel.ObtenerListaClientesAsync();
        }
        
        public int verificar_chat(int idChat, string pTipo) {
            return base.Channel.verificar_chat(idChat, pTipo);
        }
        
        public System.Threading.Tasks.Task<int> verificar_chatAsync(int idChat, string pTipo) {
            return base.Channel.verificar_chatAsync(idChat, pTipo);
        }
        
        public string ObtenerNombre(int pidChat, string pTipo) {
            return base.Channel.ObtenerNombre(pidChat, pTipo);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerNombreAsync(int pidChat, string pTipo) {
            return base.Channel.ObtenerNombreAsync(pidChat, pTipo);
        }
        
        public int verificarteclado(int pidChat, string pTipo, int pestado) {
            return base.Channel.verificarteclado(pidChat, pTipo, pestado);
        }
        
        public System.Threading.Tasks.Task<int> verificartecladoAsync(int pidChat, string pTipo, int pestado) {
            return base.Channel.verificartecladoAsync(pidChat, pTipo, pestado);
        }
        
        public int AsignarChat(int pIdChat, int pid) {
            return base.Channel.AsignarChat(pIdChat, pid);
        }
        
        public System.Threading.Tasks.Task<int> AsignarChatAsync(int pIdChat, int pid) {
            return base.Channel.AsignarChatAsync(pIdChat, pid);
        }
        
        public void UploadFile(System.IO.Stream stream) {
            base.Channel.UploadFile(stream);
        }
        
        public System.Threading.Tasks.Task UploadFileAsync(System.IO.Stream stream) {
            return base.Channel.UploadFileAsync(stream);
        }
        
        public string ObtieneRuta(int pIdChat) {
            return base.Channel.ObtieneRuta(pIdChat);
        }
        
        public System.Threading.Tasks.Task<string> ObtieneRutaAsync(int pIdChat) {
            return base.Channel.ObtieneRutaAsync(pIdChat);
        }
        
        public string ObtieneRutaF() {
            return base.Channel.ObtieneRutaF();
        }
        
        public System.Threading.Tasks.Task<string> ObtieneRutaFAsync() {
            return base.Channel.ObtieneRutaFAsync();
        }
        
        public webPrueba.ServicioChat.Empleado[] ObtenerListaEmpleados() {
            return base.Channel.ObtenerListaEmpleados();
        }
        
        public System.Threading.Tasks.Task<webPrueba.ServicioChat.Empleado[]> ObtenerListaEmpleadosAsync() {
            return base.Channel.ObtenerListaEmpleadosAsync();
        }
        
        public webPrueba.ServicioChat.Chat[] ObtenerListaChats() {
            return base.Channel.ObtenerListaChats();
        }
        
        public System.Threading.Tasks.Task<webPrueba.ServicioChat.Chat[]> ObtenerListaChatsAsync() {
            return base.Channel.ObtenerListaChatsAsync();
        }
        
        public int cambiarEstado(int idEmp, int estado) {
            return base.Channel.cambiarEstado(idEmp, estado);
        }
        
        public System.Threading.Tasks.Task<int> cambiarEstadoAsync(int idEmp, int estado) {
            return base.Channel.cambiarEstadoAsync(idEmp, estado);
        }
    }
}
