//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class chats
    {
        public long nIdChat { get; set; }
        public string cNomclient { get; set; }
        public string cTelCliente { get; set; }
        public string cEmailClien { get; set; }
        public int nEstado { get; set; }
        public Nullable<System.DateTime> dFechaIng { get; set; }
        public Nullable<System.DateTime> dFechaAte { get; set; }
        public Nullable<System.DateTime> dFechaFin { get; set; }
        public string direccionIp { get; set; }
        public string cCodigoUsu { get; set; }
        public string cTextoChat { get; set; }
        public int nCalifica { get; set; }
        public string cComenExt { get; set; }
        public string cComenInt { get; set; }
        public string UCierra { get; set; }
        public string cZona { get; set; }
    }
}
