//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int nIdUsuario { get; set; }
        public string cCodigousu { get; set; }
        public string cNomUsuari { get; set; }
        public int nIdRol { get; set; }
        public int nEstadousu { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
