//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class calculadoraCreditoEntities : DbContext
    {
        public calculadoraCreditoEntities()
            : base("name=calculadoraCreditoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lineas> lineas { get; set; }
        public virtual DbSet<monedas> monedas { get; set; }
        public virtual DbSet<correos> correos { get; set; }
        public virtual DbSet<plazos> plazos { get; set; }
    }
}
