//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineas
    {
        public int nidlineacr { get; set; }
        public string cnombrelin { get; set; }
        public decimal ntasaInter { get; set; }
        public int nidmoneda { get; set; }
    
        public virtual monedas monedas { get; set; }
    }
}
